"2": "Interactive - Keyboard"
"3": "Network Logon"
"4": "Scheduled Task / Batch Process"
"5": "Service Account"
"7": "Unlock	System"
"8": "Network Clear Text"
"9": "New Credentials"
"10": "Remote Interactive"
"11": "Cached Interactive"
"0": "System Account"