"0x0": "Success"
"0x1": "Client's entry in KDC database has expired"
"0x2": "Server's entry in KDC database has expired"
"0x3": "Requested Kerberos version number not supported"
"0x4": "Client's key encrypted in old master key"
"0x5": "Server's key encrypted in old master key"
"0x6": "Username does not exist or has not replicated"
"0x7": "Server not found in Kerberos database"
"0x8": "Multiple principal entries in KDC database"
"0x9": "The client or server has a null key (master key)"
"0xa": "Ticket (TGT) not eligible for postdating"
"0xb": "Requested start time is later than end time (time difference between the KDC and the client)"
"0xc": "Requested start time is later than end time (logon restrictions in place on user’s account)"
"0xd": "KDC cannot accommodate requested option"
"0xe": "KDC has no support for encryption type"
"0xf": "KDC has no support for checksum type"
"0x10": "KDC has no support for PADATA type (pre-authentication data)"
"0x11": "KDC has no support for transited type"
"0x12": "Account disabled, expired, locked out, logon hours restriction"
"0x13": "Credentials for server have been revoked"
"0x14": "TGT has been revoked"
"0x15": "Client not yet valid—try again later"
"0x16": "Server not yet valid—try again later"
"0x17": "Password has expired"
"0x18": "Bad Password"
"0x19": "Additional pre-authentication required"
"0x1a": "KDC does not know about the requested server"
"0x1b": "Server principal valid for user2user only"
"0x1d": "A Service is not available"
"0x1f": "Integrity check on decrypted field failed"
"0x20": "The ticket has expired - Frequently logged by Computer Accounts"
"0x21": "The ticket is not yet valid"
"0x22": "The request is a replay"
"0x23": "The ticket is not for us"
"0x24": "The ticket and authenticator do not match"
"0x25": "The clock skew is too great"
"0x26": "Network address in network layer header doesn't match address inside ticket"
"0x27": "Protocol version numbers don't match (PVNO)"
"0x28": "Message type is unsupported"
"0x29": "Message stream modified and checksum didn't match"
"0x2a": "Message out of order (possible tampering)"
"0x2c": "Specified version of key is not available"
"0x2d": "Service key not available"
"0x2e": "Mutual authentication failed"
"0x2f": "Incorrect message direction"
"0x30": "Alternative authentication method required"
"0x31": "Incorrect sequence number in message"
"0x32": "Inappropriate type of checksum in message (checksum may be unsupported)"
"0x33": "Desired path is unreachable"
"0x34": "Too much data"
"0x3c": "Generic error"
"0x3d": "Field is too long for this implementation"
"0x3e": "The client trust failed or is not implemented"
"0x3f": "The KDC server trust failed or could not be verified"
"0x40": "The signature is invalid"
"0x41": "A higher encryption level is needed"
"0x42": "User-to-user authorization is required"
"0x43": "No TGT was presented or available"
"0x44": "Incorrect domain or principal"
"0xc000005e": "No Logon Servers available to login"
"0xc0000064": "User name does not exist"
"0xc000006a": "User name is correct but the password is wrong"
"0xc000006d": "Logon Failure"
"0xc000006e": "Unknown User name or bad password"
"0xc000006f": "User tried to logon outside his day of week or time of day restrictions"
"0xc0000234": "User is currently locked out"
"0xc0000072": "Account is currently disabled"
"0xc0000070": "Workstation restriction"
"0xc00000193": "Account expiration"
"0xc0000071": "Expired password"
"0xc0000133": "Clocks between DC and other computer too far out of sync"
"0xc0000224": "User is required to change password at next logon"
"0xc0000225": "Evidently a bug in Windows and not a risk"
"0xc00002ee": "An Error occurred during Logon"
"0xc000015b": "The user has not been granted the requested logon type (aka logon right) at this machine"